language: python
python:
- 3.8
services:
- postgresql
install:
- psql -c 'create database django_db owner postgres;' -U postgres
- pip install -r requirements.txt
script:
- python manage.py migrate
- python manage.py test shop/tests/
deploy:
  provider: heroku
  api_key:
    secure: hHRe7hSDiBSNVKBVlFUyIwddKRV3CS2S0HSXl2JMlTa6rH20txJuvlV2kOb7qK2CR11RZbbI3JNSt+H1aJE1iLZG+cyOVM0l3itOGsVh5G3dLgRz2U7dPn9oC7R+vQqTcRNmg1O9yPlrmTUixBlTt+y3M8zElCcWfYX+IwFvWYLMyLzhg3MCfzWe2HWmc/zV3jqVWASVSt96MOEtxnR172+ZjY2eiTWvUTVNQ++gKSc3xGsSaGT9IkVI8jGinQ1Jd85ofa9/Jq4mu/PU0YW43YF0Ebhm8syacTLxPPqxKsgz/XA3ZfyUcOQllC0cW0nvyr3qBqv7xJaHNk1h41ba3Mqt7WSIrwke6LMDnklhq6PpLgs7A6VttN5QEnIYElnaOd5H1xLGD/RaDYIbzwqPBrNOwVlK4SaoUkxvyFl7+PTaYoeW2uVqt1M3JEiqfOZG3lCCNI53LD4u7cdfpB/mE1rAAb7Strp3NwyKeADECFlRBTNurAT93hvYiFMwFub3nWvZG1CKg3s2yOjoFvui0JyeuRwtfw4+s1Y0tHNlbL60SMKxyTUgXRvu7mVy0mV8lO99ARwxf8LY9aDzYyRwS66ctdknQIQl1pu6OJ5nKx0SALUA9zmCBtusVhk6AN874BWS/2zpXTt43ugA5s/jUdzvQIroSWV1QkFRdknVGIE=
  app: webapp-spirina-shop
  run:
  on: master
